# Generated by Django 4.2.2 on 2023-07-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0010_alter_professor_options_alter_aluno_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CursoDaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turmas.disciplina')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turmas.periodo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.professor')),
                ('turmas', models.ManyToManyField(to='turmas.turma')),
            ],
        ),
    ]
