# Generated by Django 4.2.2 on 2023-06-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoExemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('nome', models.CharField(max_length=255)),
                ('algum_texto', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
