# Generated by Django 4.2.2 on 2023-06-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alunoexemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunoExemplo',
        ),
    ]
