# Generated by Django 4.2.2 on 2023-06-27 22:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_aluno_data_nascimento_aluno_genero_alter_aluno_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('91d0210a-657f-4293-9a1d-cd660b17952b')),
        ),
    ]
