# Generated by Django 4.2.2 on 2023-06-27 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_aluno_sobrenome_aluno_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c705b194-f3d9-4491-8f29-6d43e6e5082c'), verbose_name='ID'),
        ),
    ]
