# Generated by Django 4.2.2 on 2023-07-04 20:17

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_aluno_matriculado_alter_aluno_observacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('716d2ffa-6448-48a7-8db0-4570caadc603'), verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Não informado')], default=1, verbose_name='gênero')),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now, verbose_name='data de nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('coordenador', models.BooleanField(default=False, help_text='é um coordenador atualmente?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('716d2ffa-6448-48a7-8db0-4570caadc603'), verbose_name='ID'),
        ),
    ]
