# Generated by Django 4.2.2 on 2023-07-04 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_professor_alter_aluno_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'professor', 'verbose_name_plural': 'professores'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d3747ca-16f1-4cea-b65e-4de03b31b04f'), verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d3747ca-16f1-4cea-b65e-4de03b31b04f'), verbose_name='ID'),
        ),
    ]
